# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 14:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
